$ErrorActionPreference = "Stop"
Set-Location "C:\Users\AlstonQuadros\Documents\Meeting Agent"
$env:NODE_ENV = "development"
$env:API_PORT = "3001"
$env:DATABASE_URL = "postgres://meetx:meetx@localhost:5432/meetx"
$env:REDIS_URL = "redis://localhost:6379"
$env:S3_ENDPOINT = "http://localhost:9000"
$env:S3_REGION = "eu-central-1"
$env:S3_BUCKET = "meetx-local"
$env:S3_ACCESS_KEY_ID = "meetx"
$env:S3_SECRET_ACCESS_KEY = "meetx-password"
$env:DEFAULT_DATA_REGION = "eu-central-1"
$env:CONFIG_SECRET_MANAGER = "local"
pnpm --filter @meet-x/api dev
